sisserad/clientes/urls.py
from django.urls import path
from . import views


app_name = "clientes"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:cliente_id>/equipamento/new/", views.cliente_equipamento_form, name="equipamento-form"),
    path("<int:cliente_id>/equipamento/<int:pk>/edit/", views.EquipamentoUpdateView.as_view(), name="equipamento-editar"),
    path("<int:cliente_id>/endereco/new/", views.cliente_endereco_form, name="endereco-form"),
    path("<int:cliente_id>/endereco/<int:pk>/edit/", views.EnderecoUpdateView.as_view(), name="endereco-editar"),
    path("", views.ListView.as_view(), name="list"),
    path("new/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/edit/", views.UpdateView.as_view(), name="editar"),

]

sisserad/sisserad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from servicos import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='admin/')),
    path("clientes/", include("clientes.urls")),
    path('servicos/', include('servicos.urls', namespace='servicos')),
    path("api/atividades/<int:pk>/abrir/", views.AbrirAtividade.as_view(), name="abrir_atividade"),
    path("api/atividades/<int:pk>/finalizar/", views.FinalizarAtividade.as_view(), name="finalizar_atividade"),
    path("api/atividades/<int:pk>/revisar/", views.RevisarAtividade.as_view(), name="revisar_atividade"),
    path("api/atividades/<int:pk>/publicar/", views.PublicarAtividade.as_view(), name="publicar_atividade"),
]

sisserad/clientes/models.py
from django.db import models
from core.models import BaseModel

class Cliente(BaseModel):
    id = models.AutoField(primary_key=True, editable=False, unique=True)
    nome = models.CharField(max_length=255, blank=False, null=False)
    documento = models.CharField(max_length=50, blank=False, null=False, unique=True)
    email = models.EmailField(max_length=50, blank=False, null=False, unique=True)
    telefone_fixo = models.CharField(max_length=20, blank=True, null=True)
    celular = models.CharField(max_length=20)
    

    def __str__(self):
        return f'{self.nome.capitalize()}(Documento: {self.documento})'

class Equipamento(BaseModel):
    id = models.AutoField(primary_key=True, editable=False, unique=True, help_text="Identificador único do equipamento")
    nome = models.CharField(max_length=255)
    fabricante = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    numero_serie = models.CharField(max_length=50)
    ano_fabricacao = models.IntegerField()
    parametros_variaveis = models.CharField(max_length=255, null=True, blank=True)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    endereco = models.ForeignKey('Endereco', on_delete=models.SET_NULL, blank=True, null=True)
        
    def __str__(self):
        return f'{self.nome} Nº Série: {self.numero_serie}'

class Endereco(BaseModel):
    id = models.AutoField(primary_key=True, editable=False, unique=True)
    logradouro = models.CharField(max_length=255)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=255, null=True, blank=True)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=10)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)  
        
    def __str__(self):
        return f'{self.logradouro}, {self.numero} CEP:{self.cep}'
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['cliente', 'cep', 'numero'], name='unique address for cliente')
        ]

sisserad/clientes/forms.py
from django import forms

from clientes.models import Cliente, Endereco, Equipamento


class EquipamentoForm(forms.ModelForm):
    class Meta:
        model = Equipamento
        fields = ["nome", "fabricante", "modelo", "numero_serie", "ano_fabricacao", "parametros_variaveis", "endereco"]
    def __init__(self, *args, **kwargs):
        self.cliente = kwargs.pop('cliente', None)
        super(EquipamentoForm, self).__init__(*args, **kwargs)
        if self.cliente:
            self.fields['endereco'].queryset = self.cliente.endereco_set.all()
    def save(self, commit=True):
        equipamento = super(EquipamentoForm, self).save(commit=False)
        if self.cliente:
            equipamento.cliente = self.cliente
        if commit:
            equipamento.save()
        return equipamento    
        

class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ['logradouro', 'numero', 'cep', 'cidade', 'estado']
    def __init__(self, *args, **kwargs):
        self.cliente = kwargs.pop('cliente', None)
        super(EnderecoForm, self).__init__(*args, **kwargs)

        
    def save(self, commit=True):
        endereco = super(EnderecoForm, self).save(commit=False)
        if self.cliente:
            endereco.cliente = self.cliente
        if commit:
            endereco.save()
        return endereco 
    
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nome", "documento", "email", "telefone_fixo", "celular"]

sisserad/clientes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from clientes.models import Cliente, Endereco, Equipamento
from clientes.forms import ClienteForm, EnderecoForm, EquipamentoForm
from django.views import generic


class DetailView(generic.DetailView):
    model = Cliente
    template_name = "clientes/detail.html"

class ListView(generic.ListView):
    model = Cliente
    template_name = "clientes/list.html"
    context_object_name = "latest_registered_clientes"
    def get_queryset(self):
        return Cliente.objects.order_by("-created_at")[:5]

class CreateView(generic.CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = "clientes/form.html"
    success_url = "clientes:list"
    
    def get_success_url(self):
        return reverse("clientes:detail", args=(self.object.id,))
    
    
class UpdateView(generic.UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = "clientes/form.html"

    def get_success_url(self):
        return reverse("clientes:detail", args=(self.object.id,))

class EnderecoUpdateView(generic.UpdateView):
    model = Endereco
    form_class = EnderecoForm
    template_name = "clientes/enderecos/form.html"

    def get_success_url(self):
        return reverse("clientes:detail", args=(self.object.cliente.id,))
    
class EquipamentoUpdateView(generic.UpdateView):
    model = Equipamento
    form_class = EquipamentoForm
    template_name = "clientes/equipamentos/form.html"

    def get_success_url(self):
        return reverse("clientes:detail", args=(self.object.cliente.id,))
    

def cliente_equipamento_form(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == "POST":
        form = EquipamentoForm(request.POST, cliente=cliente)
        if form.is_valid():
            form.save()
            return redirect("clientes:detail", pk=cliente_id)
    else:
        form = EquipamentoForm(cliente=cliente)
    return render(request, "clientes/equipamentos/form.html", {
        "cliente": cliente,
        "form": form,
    })
    
def cliente_endereco_form(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == "POST":
        form = EnderecoForm(request.POST, cliente=cliente)
        if form.is_valid():
            form.save()
            return redirect("clientes:detail", pk=cliente_id)
    else:
        form = EnderecoForm(cliente=cliente)
    return render(request, "clientes/enderecos/form.html", {
        "cliente": cliente,
        "form": form,
    })

sisserad/clientes/templates/clientes/detail.html
<!DOCTYPE html>
<html>
     <head>
          <style>
               {% for endereco in cliente.endereco_set.all %}
                    .editar-endereco-{{ endereco.id }} {
                    display: none;
                    }
                    
     
                    .endereco-{{ endereco.id }}:hover .editar-endereco-{{ endereco.id }} {
                         display: inline;
                    }

                    .equipamento-{{ equipamento.id }}:hover{
                         background-color: #f0f0f1;
                    }

                    .endereco-{{ endereco.id }}:hover .equipamentos-endereco-{{ endereco.id }} {
                         display: inline;
                    }
                    
                    .endereco-{{ endereco.id }} {
                         margin: 2em;
                    }


                    .endereco-{{ endereco.id }}:hover {
                         background-color: #f0f0f0;
                    }

                    .equipamentos-endereco-{{ endereco.id }} {
                         display: none;
                    }
               {% endfor %}
          </style>
     </head>
     <body>
          {% if cliente %}
          <p>{{cliente}}</p>
          <p>Endereços:</p>
          <ul class="cliente-list">
               {% for endereco in cliente.endereco_set.all %}
                    <li class="endereco-{{endereco.id}}">{{endereco}}
                      <a class="editar-endereco-{{endereco.id}}" href="{% url 'clientes:endereco-editar' pk=endereco.id cliente_id=endereco.cliente.id%}">Editar</a>
                      <div class="equipamentos-endereco-{{endereco.id}}">
                         <p>Equipamentos:</p>
                         <ul>
                              {% if not endereco.equipamento_set.all %}
                                   <li>Nenhum equipamento cadastrado nesse endereço.</li>
                              {% endif %}
                              {% for equipamento in endereco.equipamento_set.all %}
                                   <li class="equipamento-{{equipamento.id}}">
                                        {{equipamento}}
                                        <a href="{% url 'clientes:equipamento-editar' pk=equipamento.id cliente_id=endereco.cliente.id%}">Editar</a>
                                   </li>
                              {% endfor %}
                         </ul>
                      </div>
                    </li>
               {% endfor %}
          </ul>
          <a href="{% url 'clientes:list' %}">Voltar</a>
          <a href="{% url 'clientes:equipamento-form' cliente.id %}">Adicionar Equipamento</a>
          <a href="{% url 'clientes:endereco-form' cliente.id %}">Adicionar Endereço</a>
       {% endif %}
     </body>
</html>

sisserad/clientes/templates/clientes/form.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

sisserad/clientes/templates/clientes/list.html
{% load static %}
<img src="{% static 'clientes/images/seradlogo.png' %}" alt="Logo da empresa">
<link rel="stylesheet" href="{% static 'clientes/style.css' %}">


{% if latest_registered_clientes %}
    <ul>
    {% for cliente in latest_registered_clientes %}
        <li class="cliente"><a href="{% url 'clientes:detail' cliente.id %}">{{ cliente.nome }}</a> registrado em: {{cliente.created_at}}</li>
        <a href="{% url 'clientes:editar' cliente.id %}">Editar cliente</a>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há clientes disponíveis.</p>
{% endif %}
<a href="{% url 'clientes:create' %}">Adicionar cliente</a>